name: 🐛 Bug Report
description: Signaler un problème ou dysfonctionnement
title: "[BUG] "
labels: ["bug", "priority-high"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Signalement de Bug
        
        Utilisez ce template pour signaler un problème dans le projet.

  - type: textarea
    id: description
    attributes:
      label: "📝 Description du problème"
      description: "Décrivez le bug rencontré de manière détaillée"
      placeholder: "Ex: La page de connexion ne répond pas quand on clique sur 'Se connecter'..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "🔄 Étapes pour reproduire"
      description: "Comment reproduire ce bug ?"
      placeholder: |
        1. Aller sur la page...
        2. Cliquer sur...
        3. Voir l'erreur...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "✅ Comportement attendu"
      description: "Que devrait-il se passer normalement ?"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: "⚠️ Gravité"
      options:
        - "Critique (bloque tout)"
        - "Élevée (fonctionnalité majeure)"
        - "Moyenne (gêne l'utilisation)"
        - "Faible (cosmétique)"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: "💻 Environnement"
      description: "Sur quel environnement le bug apparaît ?"
      placeholder: "Navigateur, OS, version, etc."